export default class Types {

	static SHOW_POPUP = 'SHOW_POPUP'
	static CLOSE_POPUP = 'CLOSE_POPUP'

	static ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
	static REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'

	static FETCH_POSTS = 'FETCH_POSTS'
	static FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'
	static FETCH_POSTS_RESULT = 'FETCH_POSTS_RESULT'
	static FETCH_MORE_POSTS = 'FETCH_MORE_POSTS'
	static FETCH_MORE_POSTS_RESULT = 'FETCH_MORE_POSTS_RESULT'

}
